[package]
name = "femur-server"
version = "0.0.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
femur = { path = "../femur" }
tiny_http = { version = "0.9.0", features = ["ssl"] }
