[package]
name = "femur"
version = "0.0.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
